	@echo Switching to Map : Liberty
md Liberty	
cd Liberty	
	@echo Started downloads
	@echo Getting needed files from Orginal webmap
	curl https://andistyr.github.io/wu-map/14816//index.html --output index.html --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14816//map.js --output map.js --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14816//removegoogle.js --output removegoogle.js --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14816//style.css --output style.css --ssl-no-revoke
md CSS	
cd CSS	
	curl https://andistyr.github.io/wu-map/14816/css/roboto.css --output roboto.css --ssl-no-revoke
cd ..	
md images	
cd images	
	curl https://andistyr.github.io/wu-map/14816/images/deed_large.png --output deed_large.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14816/images/deed_small.png --output deed_small.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14816/images/deed_solo.png --output deed_solo.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14816/images/guard_tower.png --output guard_tower.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14816/images/poi.png --output poi.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14816/images/home_on.png --output home_on.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14816/images/home_hover.png --output home_hover.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14816/images/home_off.png --output home_off.png --ssl-no-revoke
cd..	
md scripts	
cd scripts	
	curl https://andistyr.github.io/wu-map/14816/scipts/cookies.min.js --output cookies.min.js --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14816/scipts/jquery.min.js --output jquery.min.js --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14816/scipts/transparency.min.js --output transparency.min.js --ssl-no-revoke
cd..	   
cd..	
	
	
	
	@echo Switching to Map : Novus
md Novus	
cd Novus	
	@echo Started downloads
	@echo Getting needed files from Orginal webmap
	curl https://andistyr.github.io/wu-map/14821//index.html --output index.html --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14821//map.js --output map.js --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14821//removegoogle.js --output removegoogle.js --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14821//style.css --output style.css --ssl-no-revoke
md CSS	
cd CSS	
	curl https://andistyr.github.io/wu-map/14821/css/roboto.css --output roboto.css --ssl-no-revoke
cd ..	
md images	
cd images	
	curl https://andistyr.github.io/wu-map/14821/images/deed_large.png --output deed_large.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14821/images/deed_small.png --output deed_small.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14821/images/deed_solo.png --output deed_solo.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14821/images/guard_tower.png --output guard_tower.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14821/images/poi.png --output poi.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14821/images/home_on.png --output home_on.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14821/images/home_hover.png --output home_hover.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14821/images/home_off.png --output home_off.png --ssl-no-revoke
cd..	
md scripts	
cd scripts	
	curl https://andistyr.github.io/wu-map/14821/scipts/cookies.min.js --output cookies.min.js --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14821/scipts/jquery.min.js --output jquery.min.js --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14821/scipts/transparency.min.js --output transparency.min.js --ssl-no-revoke
cd..	   
cd..	
	
	
	
	@echo Switching to Map : Caza
md Caza	
cd Caza	
	@echo Started downloads
	@echo Getting needed files from Orginal webmap
	curl https://andistyr.github.io/wu-map/14818//index.html --output index.html --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14818//map.js --output map.js --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14818//removegoogle.js --output removegoogle.js --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14818//style.css --output style.css --ssl-no-revoke
md CSS	
cd CSS	
	curl https://andistyr.github.io/wu-map/14818/css/roboto.css --output roboto.css --ssl-no-revoke
cd ..	
md images	
cd images	
	curl https://andistyr.github.io/wu-map/14818/images/deed_large.png --output deed_large.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14818/images/deed_small.png --output deed_small.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14818/images/deed_solo.png --output deed_solo.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14818/images/guard_tower.png --output guard_tower.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14818/images/poi.png --output poi.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14818/images/home_on.png --output home_on.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14818/images/home_hover.png --output home_hover.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14818/images/home_off.png --output home_off.png --ssl-no-revoke
cd..	
md scripts	
cd scripts	
	curl https://andistyr.github.io/wu-map/14818/scipts/cookies.min.js --output cookies.min.js --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14818/scipts/jquery.min.js --output jquery.min.js --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14818/scipts/transparency.min.js --output transparency.min.js --ssl-no-revoke
cd..	   
cd..	
	
	
	@echo Switching to Map : Infinity2
md Infinity2	
cd Infinity2	
	@echo Started downloads
	@echo Getting needed files from Orginal webmap
	curl https://andistyr.github.io/wu-map/14901//index.html --output index.html --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14901//map.js --output map.js --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14901//removegoogle.js --output removegoogle.js --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14901//style.css --output style.css --ssl-no-revoke
md CSS	
cd CSS	
	curl https://andistyr.github.io/wu-map/14901/css/roboto.css --output roboto.css --ssl-no-revoke
cd ..	
md images	
cd images	
	curl https://andistyr.github.io/wu-map/14901/images/deed_large.png --output deed_large.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14901/images/deed_small.png --output deed_small.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14901/images/deed_solo.png --output deed_solo.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14901/images/guard_tower.png --output guard_tower.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14901/images/poi.png --output poi.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14901/images/home_on.png --output home_on.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14901/images/home_hover.png --output home_hover.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14901/images/home_off.png --output home_off.png --ssl-no-revoke
cd..	
md scripts	
cd scripts	
	curl https://andistyr.github.io/wu-map/14901/scipts/cookies.min.js --output cookies.min.js --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14901/scipts/jquery.min.js --output jquery.min.js --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14901/scipts/transparency.min.js --output transparency.min.js --ssl-no-revoke
cd..	   
cd..	
	
	
	@echo Switching to Map : Infinity3
md Infinity3	
cd Infinity3	
	@echo Started downloads
	@echo Getting needed files from Orginal webmap
	curl https://andistyr.github.io/wu-map/14852//index.html --output index.html --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14852//map.js --output map.js --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14852//removegoogle.js --output removegoogle.js --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14852//style.css --output style.css --ssl-no-revoke
md CSS	
cd CSS	
	curl https://andistyr.github.io/wu-map/14852/css/roboto.css --output roboto.css --ssl-no-revoke
cd ..	
md images	
cd images	
	curl https://andistyr.github.io/wu-map/14852/images/deed_large.png --output deed_large.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14852/images/deed_small.png --output deed_small.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14852/images/deed_solo.png --output deed_solo.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14852/images/guard_tower.png --output guard_tower.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14852/images/poi.png --output poi.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14852/images/home_on.png --output home_on.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14852/images/home_hover.png --output home_hover.png --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14852/images/home_off.png --output home_off.png --ssl-no-revoke
cd..	
md scripts	
cd scripts	
	curl https://andistyr.github.io/wu-map/14852/scipts/cookies.min.js --output cookies.min.js --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14852/scipts/jquery.min.js --output jquery.min.js --ssl-no-revoke
	curl https://andistyr.github.io/wu-map/14852/scipts/transparency.min.js --output transparency.min.js --ssl-no-revoke
cd..	   
cd..	
	
	
